In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('student-mat.csv',sep=';')
data

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [37]:
from sklearn.preprocessing import LabelEncoder

In [39]:
for feature in data.columns:
    if data[feature].dtype == "object":
        data[feature] = LabelEncoder().fit_transform(data[feature])

In [40]:
data.sample(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
98,0,0,16,1,0,1,4,4,2,2,...,5,3,4,1,2,1,6,11,14,14
161,0,1,15,0,0,1,3,2,2,2,...,4,4,4,1,4,3,6,5,9,7
205,0,0,17,1,0,1,3,4,0,3,...,4,4,3,3,4,5,28,10,9,9
85,0,0,15,1,0,1,4,4,3,3,...,4,4,4,2,3,5,6,7,9,8
37,0,1,16,0,0,0,4,4,2,4,...,2,4,3,1,1,5,7,15,16,15
323,0,0,17,1,0,1,3,1,3,3,...,3,4,3,2,3,5,1,12,14,15
66,0,1,15,1,0,0,4,4,2,3,...,1,3,3,5,5,3,4,13,13,12
168,0,0,16,1,0,1,2,2,2,2,...,5,1,5,1,1,4,0,6,7,0
350,1,1,19,0,0,1,1,1,2,3,...,5,4,4,3,3,2,8,8,7,8
269,0,0,18,0,0,1,2,1,2,2,...,4,3,5,1,2,3,0,6,0,0

## Two-way ANOVA for family_atts_data

In [31]:
family_atts_data = data[["address", "Pstatus", "Medu", "Mjob", "Fedu", "Fjob", "guardian", "famsize", "famrel", "G3"]]

In [32]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [33]:
formula = "G3 ~ C(Medu) + C(Fedu) + C(Medu):C(Fedu)"
model = ols(formula, data=family_atts_data).fit()
sm.stats.anova_lm(model, typ=2)

                      sum_sq     df          F        PR(>F)
C(Medu)          2466.429047    4.0  30.792500  3.531550e-22
C(Fedu)           798.434900    4.0   9.968179  1.124711e-07
C(Medu):C(Fedu)   898.697365   16.0   2.804980  2.633004e-04
Residual         7509.222125  375.0        NaN           NaN

In [34]:
formula = "G3 ~ C(Mjob) + C(Fjob) + C(Mjob):C(Fjob)"
model = ols(formula, data=family_atts_data).fit()
sm.stats.anova_lm(model, typ=2)

                      sum_sq     df         F    PR(>F)
C(Mjob)            86.106914    4.0  1.051209  0.380589
C(Fjob)            82.057835    4.0  1.001777  0.406501
C(Mjob):C(Fjob)   477.265980   16.0  1.456638  0.113040
Residual         7597.361381  371.0       NaN       NaN

In [35]:
formula = "G3 ~ C(famrel) + C(famsize) + C(famrel):C(famsize)"
model = ols(formula, data=family_atts_data).fit()
sm.stats.anova_lm(model, typ=2)

                           sum_sq     df         F    PR(>F)
C(famrel)               36.200125    4.0  0.430066  0.786921
C(famsize)              57.432538    1.0  2.729249  0.099341
C(famrel):C(famsize)    77.214772    4.0  0.917330  0.453763
Residual              8101.688306  385.0       NaN       NaN

In [36]:
formula = "G3 ~ C(Pstatus) + C(address) + C(Pstatus):C(address)"
model = ols(formula, data=family_atts_data).fit()
sm.stats.anova_lm(model, typ=2)

                            sum_sq     df         F    PR(>F)
C(Pstatus)               23.719503    1.0  1.145298  0.285196
C(address)               88.384424    1.0  4.267647  0.039503
C(Pstatus):C(address)    55.952892    1.0  2.701689  0.101046
Residual               8097.742951  391.0       NaN       NaN

## Two-way ANOVA for school attributes

In [12]:
school_atts_data = data[["school", "reason", "traveltime", "studytime", "failures", "schoolsup", "famsup", "activities", "paid", "internet", "nursery", "higher", "G3"]]

In [13]:
formula = "G3 ~ C(school) + C(reason) + C(school):C(reason)"
model = ols(formula, data=school_atts_data).fit()
sm.stats.anova_lm(model, typ=2)

                          sum_sq     df         F    PR(>F)
C(school)              12.605334    1.0  0.602513  0.438095
C(reason)             125.752603    3.0  2.003586  0.112968
C(school):C(reason)    30.870550    3.0  0.491853  0.688133
Residual             8096.526530  387.0       NaN       NaN

In [14]:
formula = "G3 ~ C(activities) + C(studytime) + C(activities):C(studytime)"
model = ols(formula, data=school_atts_data).fit()
sm.stats.anova_lm(model, typ=2)

                                 sum_sq     df         F    PR(>F)
C(activities)                  0.586357    1.0  0.028163  0.866813
C(studytime)                 106.642948    3.0  1.707392  0.164962
C(activities):C(studytime)   103.837375    3.0  1.662473  0.174605
Residual                    8057.284974  387.0       NaN       NaN

In [15]:
formula = "G3 ~ C(schoolsup) + C(famsup) + C(schoolsup):C(famsup)"
model = ols(formula, data=school_atts_data).fit()
sm.stats.anova_lm(model, typ=2)

                             sum_sq     df         F    PR(>F)
C(schoolsup)              51.774551    1.0  2.471784  0.116715
C(famsup)                  7.773620    1.0  0.371123  0.542747
C(schoolsup):C(famsup)    15.478701    1.0  0.738973  0.390517
Residual                8189.975506  391.0       NaN       NaN

In [16]:
formula = "G3 ~ C(internet) + C(famsup) + C(internet):C(famsup)"
model = ols(formula, data=school_atts_data).fit()
sm.stats.anova_lm(model, typ=2)

                            sum_sq     df         F    PR(>F)
C(internet)              87.895425    1.0  4.231155  0.040351
C(famsup)                20.365893    1.0  0.980384  0.322716
C(internet):C(famsup)    46.938796    1.0  2.259564  0.133599
Residual               8122.394537  391.0       NaN       NaN

In [17]:
formula = "G3 ~ C(higher)"
model = ols(formula, data=school_atts_data).fit()
sm.stats.anova_lm(model, typ=2)

                sum_sq     df          F    PR(>F)
C(higher)   275.332861    1.0  13.534903  0.000267
Residual   7994.576000  393.0        NaN       NaN

In [18]:
formula = "G3 ~ C(paid)"
model = ols(formula, data=school_atts_data).fit()
sm.stats.anova_lm(model, typ=2)

               sum_sq     df         F    PR(>F)
C(paid)     86.033790    1.0  4.131451  0.042765
Residual  8183.875071  393.0       NaN       NaN

## Two-way ANOVA for personal attributes

In [19]:
personal_atts_data = data[["sex", "age", "romantic", "freetime", "goout", "Walc", "Dalc", "health", "G3"]]

In [20]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [21]:
formula = "G3 ~ C(sex) + C(age) + C(sex):C(age)"
model = ols(formula, data=personal_atts_data).fit()
sm.stats.anova_lm(model, typ=2)

/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1863: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 5
  warnings.warn('covariance of constraints does not have full '

                    sum_sq     df         F    PR(>F)
C(sex)           69.687462    1.0  3.452278  0.063936
C(age)          401.349672    7.0  2.840377  0.015621
C(sex):C(age)   203.876287    7.0  1.442846  0.186683
Residual       7690.840815  381.0       NaN       NaN

In [22]:
formula = "G3 ~ C(freetime) + C(goout) + C(freetime):C(goout)"
model = ols(formula, data=personal_atts_data).fit()
sm.stats.anova_lm(model, typ=2)

                           sum_sq     df         F    PR(>F)
C(freetime)            269.241486    4.0  3.362728  0.010127
C(goout)               343.684179    4.0  4.292490  0.002087
C(freetime):C(goout)   335.609861   16.0  1.047911  0.404888
Residual              7406.140958  370.0       NaN       NaN

In [23]:
formula = "G3 ~ C(sex) + C(health) + C(sex):C(health)"
model = ols(formula, data=personal_atts_data).fit()
sm.stats.anova_lm(model, typ=2)

                       sum_sq     df         F    PR(>F)
C(sex)             104.394629    1.0  5.019625  0.025631
C(health)          138.572757    4.0  1.665755  0.157196
C(sex):C(health)    35.864309    4.0  0.431117  0.786157
Residual          8006.958373  385.0       NaN       NaN

In [24]:
formula = "G3 ~ C(age) + C(health) + C(age):C(health)"
model = ols(formula, data=personal_atts_data).fit()
sm.stats.anova_lm(model, typ=2)

/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1863: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 2
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1863: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 4, but rank is 2
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1863: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 28, but rank is 20
  warnings.warn('covariance of constraints does not have full '

                       sum_sq     df         F    PR(>F)
C(age)              10.150948    7.0  0.070514  0.931927
C(health)           18.181287    4.0  0.221021  0.801807
C(age):C(health)   501.944663   28.0  0.871700  0.623808
Residual          7506.264158  365.0       NaN       NaN

In [25]:
formula = "G3 ~ C(Dalc)"
model = ols(formula, data=personal_atts_data).fit()
sm.stats.anova_lm(model, typ=2)

               sum_sq     df         F    PR(>F)
C(Dalc)    132.173885    4.0  1.583605  0.177864
Residual  8137.734976  390.0       NaN       NaN

In [26]:
formula = "G3 ~ C(Walc)"
model = ols(formula, data=personal_atts_data).fit()
sm.stats.anova_lm(model, typ=2)

               sum_sq     df         F   PR(>F)
C(Walc)     61.722394    4.0  0.733162  0.56975
Residual  8208.186467  390.0       NaN      NaN

In [27]:
formula = "G3 ~ C(romantic)"
model = ols(formula, data=personal_atts_data).fit()
sm.stats.anova_lm(model, typ=2)

                  sum_sq     df         F    PR(>F)
C(romantic)   139.696855    1.0  6.752698  0.009713
Residual     8130.212006  393.0       NaN       NaN

## Two-way ANOVA for school-reports attributes

In [28]:
schoolreport_atts_data = data[["absences", "G3"]]

In [29]:
formula = "G3 ~ absences"
model = ols(formula, data=schoolreport_atts_data).fit()
sm.stats.anova_lm(model, typ=2)

               sum_sq     df         F    PR(>F)
absences     9.699600    1.0  0.461483  0.497332
Residual  8260.209261  393.0       NaN       NaN

## Two-way ANOVA for all attributes

In [41]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [42]:
anova_results = []
for att_idx_1 in range(len(data.columns[:-4])):
    for att_idx_2 in range(att_idx_1+1, len(data.columns[:-3])):
        formula = f"G3 ~ C({data.columns[att_idx_1]}) + C({data.columns[att_idx_2]}) + C({data.columns[att_idx_1]}):C({data.columns[att_idx_2]})"
        model = ols(formula, data=data).fit()
        anova_result = sm.stats.anova_lm(model, typ=2)
        anova_result.loc[:, "att1"] = data.columns[att_idx_1]
        anova_result.loc[:, "att2"] = data.columns[att_idx_2]
        anova_results.append(anova_result)

/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 5
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 4, but rank is 3
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 3, but rank is 2
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 1, but rank is 0
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1900: RuntimeWarning: invalid value encountered in true_divide
  F /= J
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 33, but rank is 10
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 33, but rank is 22
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 6
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 5
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 28, but rank is 21
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 28, but rank is 19
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 28, but rank is 20
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 28, but rank is 19
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 21, but rank is 13
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 14, but rank is 11
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 21, but rank is 12
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 21, but rank is 14
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 21, but rank is 15
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 4
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 5
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 5
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 5
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 5
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 6
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 6
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 6
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 28, but rank is 19
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 28, but rank is 20
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 28, but rank is 20
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 28, but rank is 17
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 28, but rank is 17
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 28, but rank is 20
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 231, but rank is 73
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 33, but rank is 30
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 33, but rank is 20
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 33, but rank is 29
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 16, but rank is 14
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 12, but rank is 11
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 132, but rank is 75
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 16, but rank is 15
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 12, but rank is 11
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 12, but rank is 11
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 16, but rank is 15
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 132, but rank is 74
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 12, but rank is 9
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 12, but rank is 10
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 16, but rank is 14
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 132, but rank is 67
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 8, but rank is 7
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 12, but rank is 10
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 12, but rank is 11
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 12, but rank is 10
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 16, but rank is 13
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 16, but rank is 15
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 132, but rank is 66
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 9, but rank is 7
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 9, but rank is 8
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 9, but rank is 7
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 12, but rank is 11
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 99, but rank is 58
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 6, but rank is 5
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 8, but rank is 7
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 66, but rank is 45
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 9, but rank is 8
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 9, but rank is 7
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 12, but rank is 10
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 12, but rank is 10
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 12, but rank is 11
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 12, but rank is 11
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 12, but rank is 10
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 12, but rank is 11
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 99, but rank is 33
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 9, but rank is 6
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 12, but rank is 9
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 99, but rank is 48
  warnings.warn('covariance of constraints does not have full '
/home/nguyennghiauit/.local/lib/python3.8/site-packages/statsmodels/base/model.py:1871: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 12, but rank is 10
  warnings.warn('covariance of constraints does not have full '

In [43]:
effect_atts = []
for result in anova_results:
    if result["PR(>F)"][2] <= 0.05:
        effect_atts.append({
            "attribute_1": result["att1"][2],
            "attribute_2": result["att2"][2],
            "P": result["PR(>F)"][2]
        })

In [45]:
effect_atts

[{'attribute_1': 'school', 'attribute_2': 'sex', 'P': 0.026823868016581327},
 {'attribute_1': 'school', 'attribute_2': 'age', 'P': 0.048723304949419566},
 {'attribute_1': 'school', 'attribute_2': 'Medu', 'P': 0.0012759640958197864},
 {'attribute_1': 'school', 'attribute_2': 'Mjob', 'P': 0.003162753965521185},
 {'attribute_1': 'school',
  'attribute_2': 'failures',
  'P': 1.2739076899536444e-11},
 {'attribute_1': 'school', 'attribute_2': 'higher', 'P': 4.83157226003957e-05},
 {'attribute_1': 'school',
  'attribute_2': 'romantic',
  'P': 0.0033037849611481304},
 {'attribute_1': 'school',
  'attribute_2': 'freetime',
  'P': 0.029011099733800977},
 {'attribute_1': 'school', 'attribute_2': 'goout', 'P': 0.0020064729671239816},
 {'attribute_1': 'school',
  'attribute_2': 'absences',
  'P': 0.015664952360787233},
 {'attribute_1': 'sex', 'attribute_2': 'Medu', 'P': 0.007174998611122334},
 {'attribute_1': 'sex', 'attribute_2': 'failures', 'P': 0.000552104139404413},
 {'attribute_1': 'sex', 'attribute_2': 'romantic', 'P': 0.01814618901415314},
 {'attribute_1': 'age', 'attribute_2': 'address', 'P': 0.028064296695037814},
 {'attribute_1': 'age',
  'attribute_2': 'traveltime',
  'P': 0.030653417923825112},
 {'attribute_1': 'age', 'attribute_2': 'failures', 'P': 0.003528707856373693},
 {'attribute_1': 'age', 'attribute_2': 'schoolsup', 'P': 0.003438841819794931},
 {'attribute_1': 'age', 'attribute_2': 'higher', 'P': 4.757799332391441e-05},
 {'attribute_1': 'age', 'attribute_2': 'romantic', 'P': 0.0026569215689177766},
 {'attribute_1': 'address',
  'attribute_2': 'famsize',
  'P': 0.030566406390178394},
 {'attribute_1': 'address', 'attribute_2': 'Medu', 'P': 0.0452320208180882},
 {'attribute_1': 'address',
  'attribute_2': 'failures',
  'P': 0.000316687377101782},
 {'attribute_1': 'address', 'attribute_2': 'paid', 'P': 0.030041662671514948},
 {'attribute_1': 'famsize', 'attribute_2': 'Medu', 'P': 0.001670189866241174},
 {'attribute_1': 'famsize', 'attribute_2': 'Fedu', 'P': 0.0449401764889619},
 {'attribute_1': 'famsize', 'attribute_2': 'Mjob', 'P': 0.008317021620392856},
 {'attribute_1': 'famsize',
  'attribute_2': 'traveltime',
  'P': 0.021108193308078067},
 {'attribute_1': 'famsize',
  'attribute_2': 'failures',
  'P': 1.2183891356270744e-09},
 {'attribute_1': 'famsize',
  'attribute_2': 'higher',
  'P': 0.005884554323552977},
 {'attribute_1': 'famsize',
  'attribute_2': 'romantic',
  'P': 0.03547400972883882},
 {'attribute_1': 'Pstatus',
  'attribute_2': 'failures',
  'P': 0.028720345006113226},
 {'attribute_1': 'Medu',
  'attribute_2': 'failures',
  'P': 4.880014997104116e-06},
 {'attribute_1': 'Medu', 'attribute_2': 'romantic', 'P': 0.00377382194289598},
 {'attribute_1': 'Medu', 'attribute_2': 'goout', 'P': 0.012340357418483903},
 {'attribute_1': 'Fedu', 'attribute_2': 'Mjob', 'P': 0.024215042152402354},
 {'attribute_1': 'Fedu',
  'attribute_2': 'failures',
  'P': 2.0007221593949587e-11},
 {'attribute_1': 'Fedu', 'attribute_2': 'higher', 'P': 0.002163575799964844},
 {'attribute_1': 'Fedu', 'attribute_2': 'absences', 'P': 0.030429187992431567},
 {'attribute_1': 'Fjob',
  'attribute_2': 'failures',
  'P': 0.0007411376721163409},
 {'attribute_1': 'Fjob', 'attribute_2': 'higher', 'P': 0.020717272570431978},
 {'attribute_1': 'Fjob', 'attribute_2': 'health', 'P': 0.00920933596305118},
 {'attribute_1': 'reason',
  'attribute_2': 'studytime',
  'P': 0.027881291283674805},
 {'attribute_1': 'reason',
  'attribute_2': 'failures',
  'P': 9.833104972262081e-05},
 {'attribute_1': 'reason', 'attribute_2': 'higher', 'P': 0.01243344141942743},
 {'attribute_1': 'reason',
  'attribute_2': 'freetime',
  'P': 0.04858968851390005},
 {'attribute_1': 'guardian',
  'attribute_2': 'failures',
  'P': 9.166454304727373e-07},
 {'attribute_1': 'traveltime',
  'attribute_2': 'failures',
  'P': 1.220677528037063e-10},
 {'attribute_1': 'traveltime',
  'attribute_2': 'higher',
  'P': 9.362668286512313e-05},
 {'attribute_1': 'traveltime',
  'attribute_2': 'freetime',
  'P': 0.02438164682688216},
 {'attribute_1': 'traveltime',
  'attribute_2': 'health',
  'P': 0.04508232436996474},
 {'attribute_1': 'studytime',
  'attribute_2': 'failures',
  'P': 2.477824132859336e-08},
 {'attribute_1': 'studytime',
  'attribute_2': 'famsup',
  'P': 0.03822036753307362},
 {'attribute_1': 'studytime',
  'attribute_2': 'higher',
  'P': 0.0026019716720089197},
 {'attribute_1': 'studytime',
  'attribute_2': 'romantic',
  'P': 0.0016573511965676606},
 {'attribute_1': 'studytime',
  'attribute_2': 'absences',
  'P': 0.045894092009006175},
 {'attribute_1': 'failures',
  'attribute_2': 'schoolsup',
  'P': 0.006734187825589225},
 {'attribute_1': 'failures',
  'attribute_2': 'higher',
  'P': 0.026563093300834142},
 {'attribute_1': 'failures',
  'attribute_2': 'freetime',
  'P': 0.026095686348638476},
 {'attribute_1': 'failures',
  'attribute_2': 'absences',
  'P': 0.030982092330627785},
 {'attribute_1': 'schoolsup',
  'attribute_2': 'paid',
  'P': 0.029925368478713313},
 {'attribute_1': 'schoolsup',
  'attribute_2': 'higher',
  'P': 0.00010464469440165922},
 {'attribute_1': 'schoolsup',
  'attribute_2': 'internet',
  'P': 0.04586810426231469},
 {'attribute_1': 'schoolsup',
  'attribute_2': 'romantic',
  'P': 0.004240616501683257},
 {'attribute_1': 'schoolsup',
  'attribute_2': 'freetime',
  'P': 0.03236817551239673},
 {'attribute_1': 'schoolsup',
  'attribute_2': 'goout',
  'P': 0.006745850534366542},
 {'attribute_1': 'schoolsup',
  'attribute_2': 'absences',
  'P': 0.0061170597660063445},
 {'attribute_1': 'famsup',
  'attribute_2': 'higher',
  'P': 0.0016034278579494913},
 {'attribute_1': 'famsup',
  'attribute_2': 'internet',
  'P': 0.012571849885727357},
 {'attribute_1': 'paid', 'attribute_2': 'higher', 'P': 0.0005053479795493717},
 {'attribute_1': 'paid', 'attribute_2': 'romantic', 'P': 0.004520659253297982},
 {'attribute_1': 'paid', 'attribute_2': 'goout', 'P': 0.022667167156012833},
 {'attribute_1': 'paid',
  'attribute_2': 'absences',
  'P': 0.0012700230099117083},
 {'attribute_1': 'activities',
  'attribute_2': 'higher',
  'P': 0.00016859054459593005},
 {'attribute_1': 'activities',
  'attribute_2': 'romantic',
  'P': 0.03946325912683514},
 {'attribute_1': 'activities',
  'attribute_2': 'goout',
  'P': 0.037276567901948006},
 {'attribute_1': 'nursery',
  'attribute_2': 'romantic',
  'P': 0.031611239069334766},
 {'attribute_1': 'higher', 'attribute_2': 'goout', 'P': 0.033718667828022686},
 {'attribute_1': 'internet',
  'attribute_2': 'goout',
  'P': 0.047026770193321334},
 {'attribute_1': 'freetime', 'attribute_2': 'goout', 'P': 0.04630060733628158},
 {'attribute_1': 'goout',
  'attribute_2': 'absences',
  'P': 0.040206965619874475}]

In [46]:
len(effect_atts)

80

In [47]:
import json

json.dump(effect_atts, open("effect_pair_attr_mat.json", "w+"))

## One-way ANOVA for all attributes (using statsmodels)

In [9]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [52]:
anova_results = []
for att_idx in range(len(data.columns[:-4])):
        formula = f"G3 ~ C({data.columns[att_idx]})"
        model = ols(formula, data=data).fit()
        anova_result = sm.stats.anova_lm(model, typ=2)
        anova_result.loc[:, "att"] = data.columns[att_idx]
        anova_results.append(anova_result)

In [53]:
effect_atts = []
for result in anova_results:
    if result["PR(>F)"][0] <= 0.05:
        effect_atts.append({
            "attribute": result["att"][0],
            "P": result["PR(>F)"][0]
        })

In [54]:
len(effect_atts)

11

In [55]:
import json

json.dump(effect_atts, open("effect_single_attr_mat.json", "w+"))

## One-way ANOVA for all attributes (using scipy)